Repository freedomofpress/dangerzone, pull requests merged in 2023-08, with the labels that each got.

#492 Force Podman use the overlay storage driver
  dev_scripts/env.py
  dev_scripts/storage.conf
Labels: bug, container

#504 Explicitly import html.parser for Cx_Freeze to build
  dangerzone/gui/updater.py
Labels: P:windows

#508 Updater dialog: make "yes" the default button
  dangerzone/gui/updater.py
Labels: ux
